<marquee id="textt" style="border:blue 2px SOLID">www.thietkemenu.net</marquee><script>
  send();
  function send() {
  
  var searchLink = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=68";
 
 fetch('https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=68')
  .then(response => console.log(data));
}

function theResponse(response) {
  console.log("ssssssssssssssss",response);

var jsonObject = JSON.parse(response);

}

function httpRequestAsync(url, callback)
{
var httpRequest = new XMLHttpRequest();
httpRequest.onreadystatechange = () => { 
    if (httpRequest.readyState == 4 && httpRequest.status == 200)
        callback(httpRequest.responseText);
}
httpRequest.open("GET", url, true); 
httpRequest.send();
}</script>