<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Weather Application</title>
	<style>
div.widget3
{
  position: relative;
    width: 400px;

    height: 220px;
    background-color: #fcfdfd;
    border-radius: 9px;
    padding: 25px;
    padding-right: 30px;
    box-shadow: 0px 31px 35px -26px #080c21;
    cursor: pointer;
}

div.left-panel2
{
  
}

div.date
{
  font-size: 14px;
  font-weight: bold;
  color: rgba(0,0,0,0.5);
}

div.city
{
  font-size: 21px;
  font-weight: bold;
  text-transform: uppercase;
  padding-top: 5px;
  color: rgba(0,0,0,0.7);
}

div.temp2
{
  font-size: 51px;
  color: rgba(0,0,0,0.9);
  font-weight: 100;
  display: flex;
}

div.panel2
{
  display: inline-block;
}
#temp2
{
    width: 100px;
    height: auto;
}
div.right-panel2
{
  position: absolute;
  float: right;
  top: 0;
  margin-top: 35px;
  padding-left: 10px;
}
</style>
    
</head>

<body class="body1" >
    

        <div class="widget3" onclick="redirecttt()">
            
            <div class="left-panel2 panel2">
                <div id="date">
                    Monday, 20 Aug 2018
                </div>
                <div id="city-name2">
                    Mumbai
                </div>
                <div class="temp2">
                <img src="" alt="" id="icon2" >
                   <div id= "temp2">27&deg;</div>
                </div>
            </div>
            <div class="right-panel2 panel2">
            <img src="http://1.bp.blogspot.com/-y1qO7Tcwxbs/VhQgabbmhxI/AAAAAAAADrw/sbGFg2-W2SM/s320/vietnam%2Bvector105-thaprua-hohoankiem%2B.jpg" alt="" width="160">
            </div>
            <footer id ="textfooter">sssssssssssssss</footer>
        </div>
       
       

    
    
    <script >
    const appKey = "ff532977349290d86ac2bc3243a8ca5a";


  var cityName2 = document.getElementById("city-name2"),


  temperature2 = document.getElementById("temp2"),

 humidity = document.getElementById("humidity-div");
  datee = document.getElementById("date"),
  icon2 = document.getElementById("icon2"),
  textfooter = document.getElementById("textfooter"),

findWeatherDetails();
getdatee();

function enterPressed(event) {
  if (event.key === "Enter") {
    findWeatherDetails();
  }
}

function findWeatherDetails() {
  
    var searchLink = "https://api.openweathermap.org/data/2.5/weather?q=" + "Hanoi" + "&appid="+appKey;
   httpRequestAsync(searchLink, theResponse);
  
 }

function theResponse(response) {
  var jsonObject = JSON.parse(response);
//cityName.innerHTML = jsonObject.name; 
  cityName2.innerHTML = jsonObject.name;

 
  icon2.src = "https://s3-us-west-2.amazonaws.com/s.cdpn.io/162656/"+jsonObject.weather[0].icon+".svg";
  //"https://s3-us-west-2.amazonaws.com/s.cdpn.io/162656/"+jsonObject.weather[0].icon+".svg"

  textfooter.innerHTML = jsonObject.weather[0].description;


  temperature2.innerHTML = parseInt(jsonObject.main.temp - 273)+ "°";
}

function httpRequestAsync(url, callback)
{
  var httpRequest = new XMLHttpRequest();
  httpRequest.onreadystatechange = () => { 
      if (httpRequest.readyState == 4 && httpRequest.status == 200)
          callback(httpRequest.responseText);
  }
  httpRequest.open("GET", url, true); 
  httpRequest.send();
}

function getdatee()
{
    var days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
    var months = ['January','February','March','April','May','June','July','August','September','October','November','December'];

    var today = new Date();
    var date = days[today.getDay()] + ', '+ months[today.getMonth()]+' '+today.getDate()+', '+today.getFullYear();

    datee.innerHTML = date;

}

function redirecttt(){
  window.location.href = "http://yourname.magento.com/Weather1";
}
</script>

</body>

</html>


